### ISSUE TITLE
phosphophy and quartz dont work with origins forge

### ISSUE THREAD

**Issue by pou123** [BiggerSeries/Quartz#7]
heres the whole error sorry i dont explain what my  bug is but ive got so big of a headache

---- Minecraft Crash Report ----
// There are four lights!

Time: 4/1/22, 1:34 PM
Description: Quartz failed to startup

java.lang.NoClassDefFoundError: net/roguelogix/phosphophyllite/config/ConfigManager
	at net.roguelogix.quartz.QuartzConfig.<clinit>(QuartzConfig.java:21) ~[quartz-1.18.1-0.0.0-beta.0.2.jar%2367!/:0.0.0-beta.0.2] {re:classloading}
	at net.roguelogix.quartz.internal.QuartzCore.<clinit>(QuartzCore.java:36) ~[quartz-1.18.1-0.0.0-beta.0.2.jar%2367!/:0.0.0-beta.0.2] {re:mixin,re:classloading}
	at net.roguelogix.quartz.internal.EventListener.<clinit>(EventListener.java:28) ~[quartz-1.18.1-0.0.0-beta.0.2.jar%2367!/:0.0.0-beta.0.2] {re:mixin,re:classloading}
	at com.mojang.blaze3d.platform.Window.handler$zcm000$startQuartz(Window.java:577) ~[client-1.18.1-20211210.034407-srg.jar%2371!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quartz.mixins.json:QuartzStartupMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.platform.Window.<init>(Window.java:106) ~[client-1.18.1-20211210.034407-srg.jar%2371!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quartz.mixins.json:QuartzStartupMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.18.1-20211210.034407-srg.jar%2371!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[client-1.18.1-20211210.034407-srg.jar%2371!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.1-20211210.034407-srg.jar%2371!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.2.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
Caused by: java.lang.ClassNotFoundException: net.roguelogix.phosphophyllite.config.ConfigManager
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1053400336 bytes (1004 MiB) / 2044723200 bytes (1950 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 10
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc8
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1273
	Graphics card BiggerSeries/Phosphophyllite#1 name: NVIDIA GeForce GTX 650
	Graphics card BiggerSeries/Phosphophyllite#1 vendor: NVIDIA (0x10de)
	Graphics card BiggerSeries/Phosphophyllite#1 VRAM (MB): 2048.00
	Graphics card BiggerSeries/Phosphophyllite#1 deviceId: 0x0fc6
	Graphics card BiggerSeries/Phosphophyllite#1 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot BiggerSeries/Phosphophyllite#1 capacity (MB): 8192.00
	Memory slot BiggerSeries/Phosphophyllite#1 clockSpeed (GHz): 2.67
	Memory slot BiggerSeries/Phosphophyllite#1 type: DDR4
	Virtual memory max (MB): 33269.52
	Virtual memory used (MB): 14096.97
	Swap memory total (MB): 17024.00
	Swap memory used (MB): 2347.08
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m

**Comment by RogueLogix** [comment]
fixed with 89439099d2291f1f30f6f754e0818f305cebbfcd, first released in beta-1.2
